Preparing test test_five_failfast_on_third
OperationNumber: Op1
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op2
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelay: 1 - 1
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op3
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelay: 1 - 2
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False
Set to fail fast

OperationNumber: Op4
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelay: 1 - 3
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op5
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelay: 1 - 4
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

Calling Op1: Success True
Calling Op2: Success True
Calling Op3: Success True
OnRevertedCallbackAsync: Reverted.
Run Log:
[*time*][Op1]: Start Executing Op1
[*time*][Op1]: Op1 Success
[*time*][Op2]: Start Executing Op2
[*time*][Op2]: Op2 Success
[*time*][Op3]: Start Executing Op3
[*time*][Op3]: Op3 Failed Fast.
[*time*][Op1]: Start Executing Revert Op1
[*time*][Op1]: No undo operation for Op1. Marking as reverted
[*time*][Op2]: Start Executing Revert Op2
[*time*][Op2]: No undo operation for Op2. Marking as reverted
[*time*][Op3]: Start Executing Revert Op3
[*time*][Op3]: No undo operation for Op3. Marking as reverted
[*time*][Op4]: Saga test is not reverting not started operation Op4.
[*time*][Op5]: Saga test is not reverting not started operation Op5.


OnSagaCompleted: Id: test Status: Reverted

*** Telemetry ***
1: StartSaga - SagaID: test, Type: SagaOperations
2: StartOperation - SagaID: test, Operation: Op1
3: EndOperation - SagaID: test, Operation: Op1, Outcome: Succeeded
4: StartOperation - SagaID: test, Operation: Op2
5: EndOperation - SagaID: test, Operation: Op2, Outcome: Succeeded
6: StartOperation - SagaID: test, Operation: Op3
7: EndOperation - SagaID: test, Operation: Op3, Outcome: Failed
8: CustomEvent - SagaID: test, Event: SagaFailure, Properties: None
9: EndSaga - SagaID: test, Outcome: Reverted
