Preparing test test_five_throw_on_fifth
OperationNumber: Op1
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op2
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op3
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op4
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: empty
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

OperationNumber: Op5
Dependencies: 0
MaxRetries: 0
NumberOfFailures: 0
CallDelays: empty
RetryDelay: 0
RevertMaxRetries: 0
RevertNumberOfFailures: 0
RevertCallDelay: empty
RevertRetryDelay: 0
ValidateFunctionResults: empty
RevertValidateFunctionResults: empty
CallCounter: 0
RevertCallCounter: 0
ValidateCallCounter: 0
RevertValidateCallCounter: 0
Deactivate: empty
ThrowException: 1
ValidateThrowException: empty
RevertThrowException: empty
RevertValidateThrowException: empty
HasReportFail: False
HasRevert: False
HasValidate: False
HasRevertValidate: False

Calling Op1: Success True
Calling Op2: Success True
Calling Op3: Success True
Calling Op4: Success True
OnRevertedCallback: Reverted.
Run Log:
[*time*][Op1]: Start Executing 
[*time*][Op1]: Success
[*time*][Op2]: Start Executing 
[*time*][Op2]: Success
[*time*][Op3]: Start Executing 
[*time*][Op3]: Success
[*time*][Op4]: Start Executing 
[*time*][Op4]: Success
[*time*][Op5]: Start Executing 
[*time*][Op5]: Error when calling . Error: Throwing exception on call 1. Retry in 00:00:00 seconds
[*time*][Op5]: No reminder set for Op5. Taking failure action
[*time*][Op5]: Failed. Retries exhausted.
[*time*][Op1]: Start Executing Revert 
[*time*][Op1]: No undo operation for Op1. Marking as reverted
[*time*][Op2]: Start Executing Revert 
[*time*][Op2]: No undo operation for Op2. Marking as reverted
[*time*][Op3]: Start Executing Revert 
[*time*][Op3]: No undo operation for Op3. Marking as reverted
[*time*][Op4]: Start Executing Revert 
[*time*][Op4]: No undo operation for Op4. Marking as reverted
[*time*][Op5]: Start Executing Revert 
[*time*][Op5]: No undo operation for Op5. Marking as reverted


OnSagaCompleted: Id: test Status: Reverted
